language: node_js
node_js:
- '8'
dist: trusty
services:
- mongodb
- redis-server
env:
- NODE_ENV=ci PORT=3000
cache:
  directories:
  - node_modules
  - client/node_modules
install:
- npm install
- npm run build
script:
- nohup npm run start &
- sleep 3
- npm run test
deploy:
  provider: heroku
  api_key:
    secure: cTyVtZEmJv7tu8Q6JwRzrhU5vVEBhoeYk+QaE9ljht6Sv7eFyYSZj9pLfLZ1eQLQffwfuGLW/cAqpUftdxOCjVqNT9tB85C2oUpJiowK89EFvm28kmVWVxcAgUj/v84J5A94bjovA20wb0yFED2YTbHQDZx6aQ7imjw42wqels2pLoXGustpw7qG1Gg5KzYlJZMjHD32q8nAy7f9KMCogYf1Z9VXWGx0gIgUhLGB3wR8ZKre1LDvjTpAoX+yzBLvXfDO6CsaXjJBZU/3R6pvexPwzUK3Ogk0+yukyq+SBQDwDChWo1UQsgIl+YJxUl0QXuHUTUNtWjbyz5gLA3g8ultClD9qmUK5XsMCi9DHJjO9L1xslxTWLgE8WPVvuTBbqSlwM06B1BPHBm79a76y8TZZvd4K0UIOIFrbGY2iDyZNOyiM9ZAMAZLKiRvVvI0hGip9NtEz25b3xuzHl50/mQ2YyztUWBwbFc9zZzSd4fEs8AHPyp8cxrjntRC7i+kP5nn+qAscVVDOqIhL9rPpiBZvTxPe0dSV8OZevPegWgo9OXQsKhExfxhBUBGiO2DI1x7TaS2kOQ7vDIfITRpogUEzGCrWtPMNv6s5eW5K7a+3Zv9RUwOU+55+JCfSouBqhyeWK3RNPsLnG6mHPQ3OVKziq7LsbOAhzaw5qKx/hSM=
  app: advnodesetup
  on:
    repo: artokun/AdvancedNodeSetup
    branch: heroku-deploy
